language: ruby
cache:
  bundler: true
  yarn: true
dist: xenial
services:
  - mysql
branches:
  only:
    - master
    - stable
    - cypress
addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      - libgconf-2-4
env:
  global:
    - HEADLESS=true
    - RAILS_DB_ADAPTER=mysql2
    - RAILS_DB_NAME=hitobito_test
    - RAILS_ENV=development
rvm:
  - 2.2.3
  - 2.3.1
  - 2.4.0
  - 2.5.1
before_install:
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=1.17.3-1
install:
  - unset BUNDLE_GEMFILE # we bundle in different directories
  - export HITOBITO_BRANCH=$([ $TRAVIS_BRANCH = 'stable'] && echo ${TRAVIS_BRANCH} || echo 'master')
  - cd .. && git clone https://github.com/hitobito/hitobito_youth.git hitobito_youth
  - cd hitobito_youth && git checkout -f $HITOBITO_BRANCH
  - cd .. && git clone https://github.com/hitobito/hitobito.git hitobito
  - cd hitobito && git checkout -f $HITOBITO_BRANCH
  - export HITOBITO_CORE_DIR=$PWD
  - cp -v Wagonfile.ci Wagonfile
  - rvm use $TRAVIS_RUBY_VERSION --fuzzy
  - gem install bundler --version 1.9.10
  - bundle install --path vendor/bundle
  - for d in ../hitobito_*; do cd $d && cp -v $HITOBITO_CORE_DIR/Gemfile.lock ./ && rvm use $TRAVIS_RUBY_VERSION --fuzzy && bundle install --path vendor/bundle; done
  - cd ../hitobito_pbs/spec && yarn install --frozen-lockfile --non-interactive
  - cd $HITOBITO_CORE_DIR && rvm use $TRAVIS_RUBY_VERSION --fuzzy
script:
  - bundle exec rake db:create ci:wagon --trace
  - bundle exec rake db:drop db:create db:migrate wagon:migrate db:seed wagon:seed
  - bundle exec rails server -e test -p 5002 &
  - cd ../hitobito_pbs/spec && yarn run cypress:run --record
matrix:
  allow_failures:
  - rvm: 2.3.1
  - rvm: 2.4.0
  - rvm: 2.5.1
